name: 'Project Release'

on:
  workflow_dispatch:
    inputs:
      project_repo:
        description: "Repository with project code"
        required: true
        default: "project-"

      release_tag:
        description: "Project release number or tag (e.g. v1.0.0)"
        required: true
        default: "v"

jobs:
  check:
    runs-on: ubuntu-latest
    name: Project Version

    outputs:
      results_name: "${{ steps.check-release.outputs.results_name }}"
      results_json: "${{ steps.check-release.outputs.results_json }}"

    steps:
      - name: 'Check Release'
        id: check-release
        uses: usf-cs272-fall2022/action-project-release@main
        with:
          project_repo: "${{ inputs.project_repo }}"
          release_tag:  "${{ inputs.release_tag }}"

      - name: 'Action Outputs'
        id: action-outputs
        shell: bash
        run: |
          echo "${{ toJSON(steps.check-release.outputs) }}"

  result:
    runs-on: ubuntu-latest
    name: Output Results
    needs: check

    env:
      RESULTS_NAME: "${{ needs.check.outputs.results_name }}"
      RESULTS_JSON: "${{ needs.check.outputs.results_json }}"

    steps:
      - name: Download Results
        id: download-results
        uses: actions/download-artifact@v3
        with:
          name: '${{ env.RESULTS_NAME }}'

      - name: Display Results
        id: display-results
        uses: actions/github-script@v6
        with:
          script: |
            const output = require(`./${process.env.RESULTS_JSON}`);
            for (const property in output) {
              core.info(`${property}: ${JSON.stringify(output[property])}`);
            }
            core.info('');
            return output;
